### ISSUE TITLE
Minimize, Maximize, and Close buttons disappeared

### ISSUE THREAD

**Issue by qqwxp** [yoyurec/logseq-awesome-ui#67]
**Info:**
- OS: windows 11
- Logseq ver: v0.9.9
- Plugin ver: v2.2.6
- Theme name: Awesome Styler 

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The top right corner 3 buttons, i.e. Minimize, Maximize, and Close are gone.

**Expected behavior:**
I should be able to click three buttons on the right corner.

**Screenshots**
Plugin disabled
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/10953292/ad8c936d-9aed-4d50-92e1-ea02ac577dac)

Plugin enabled
![image](https://github.com/yoyurec/logseq-awesome-ui/assets/10953292/63b39ee6-f390-4e24-94f7-9404187c6a32)

**Comment by iBeACoder** [comment]
I have also been facing this same issue for a couple of weeks now.

OS: Kubuntu 22.04.2 LTS

Logseq ver: v0.9.10

Plugin ver: v2.2.6

Theme name: Default Dark Theme

**Comment by hasecilu** [comment]
I also have the same problem but only appears when using the right sidebar. The icons move to the right instead of staying in place.

I also saw the arrows artifact when customizing the settings but a restart fixed it.

OS: Arch Linux
Logseq ver: v0.9.11-1
Plugin ver: v2.2.6
Theme name: Oxford Blue theme dark
![Bug ft. Bocchi the cursor](https://github.com/yoyurec/logseq-awesome-ui/assets/53124818/c758987a-a7f5-4e9c-ba1c-d44d62edc1dc)

**Comment by yoyurec** [comment]
fixed!
